### ISSUE TITLE
Button to fix a processing range for all channels

### ISSUE THREAD

**Issue by taniabarkat** [ivan-usov/BrainSoundLab#10]
When looking at these data I was wondering whether it would be possible to add (and not replace) a button for the processing range, so that it would be possible to fix the processing range for all channels and all conditions in a block. This fixed processing range could then be entered by the user (for example from 0 to 50ms). I realized that this option would be useful for the deviant tone because 1) the experiments are done in awake mice, where the spiking probability is much less stable, and hence the calculated processing range regularly off  2) I wanted to compare the PSTH for the standard and deviant tone, but within the same processing window – and for now this is possible but has to be re-set whenever we go from one to the other condition again. Having it fixed for the whole block could be a welcomed option in some cases. Probably also for other analysis than Deviant Tone, so I thought that it might be better to add this in the basic analysis of the raster?

**Comment by ivan-usov** [comment]
Should be fixed in 44ac5149158ca94bd512ac21e68926590eae4574

**Comment by taniabarkat** [comment]
You are amazing, thanks a lot Ivan. I will test it on Monday.

Best
Tania

---------------------------
Tania Rinaldi Barkat
Assistant Professor in Neurophysiology

Basel University
Department of Biomedicine, room 7001
Klingelbergstrasse 50-70
4056 Basel
Switzerland

+41 61 207 1638
www.brainsoundlab.com

**Comment by ivan-usov** [comment]
Seems that 'timeRasterMod' in insufficient to fix this issue.
