### ISSUE TITLE
Saving the data from the cluster analysis

### ISSUE THREAD

**Issue by taniabarkat** [ivan-usov/BrainSoundLab#7]
How is the data saved when there is more than one cluster per channel? I guess that the average of all these clusters is then saved, but would it be possible to have each individual clusters of a channel saved too? This problem does not arise when there is not more than one cluster per channel.

One little detail: could the default name of the save file have a prefix (for example BSL) to distinguish it from the file with the raw data?

**Comment by ivan-usov** [comment]
The data for clusters is saved without any averages and is located under `block.filtSpikes(1).map` (`block.filtSpikes(1)` and `block.filtSpikes(2)` are for 'Cluster' and 'Single unit' property respectively). In other words, the cluster number for each individual spike timing `block.spikeTimings_sup{<electrode channel>}(<spike number>)` can be extracted via `block.filtSpikes(1).map{<electrode channel>}(<spike number>)`.

I see that the 'saved_data.txt' reference file is missing this info, so it need to be fixed.
