### ISSUE TITLE
Correcting the calculation of trf_rate for AMS

### ISSUE THREAD

**Issue by taniabarkat** [ivan-usov/BrainSoundLab#8]
trf_rate is not calculating correctly because the function block.calcSweepTime() (called in line 53 in process.calcTuningCruves.m) is not adapted for AMS (it is though correct for FMS). The calculation of trf_num is correct for both AMS and FMS.

**Comment by ivan-usov** [comment]
Indeed, the sweep time should be directly extracted from the second stimulus condition in AMS experiments

**Comment by taniabarkat** [comment]
Thank you Ivan. I checked the new code. We just need to add the abs value of experiment.AMS.m  line 32:

sweepTime = abs(this.stimConditions(:, 2)/1000);

And then it is all fixed.

Let me know if you want me to make that change – but I guess that as it is your repository you should do it.

Have a good start fo the week
Best

---------------------------
Tania Rinaldi Barkat
Assistant Professor in Neurophysiology

Basel University
Department of Biomedicine, room 7001
Klingelbergstrasse 50-70
4056 Basel
Switzerland

+41 61 267 1638
www.brainsoundlab.com

**Comment by ivan-usov** [comment]
I added abs(...) in 7e47c8f, so you don't need to change anything
